### ISSUE TITLE
Remove schema descriptions from Selected Elements component

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#479]
Feedback from users has revealed that the schema descriptions are disruptive to the overall user experience in the graph page. This is often the case when we have large descriptions of a particular edge/entity description.

Since we provide this detailed information in the schema page, it seems justified to remove it from this component. 

Users have highlighted that these descriptions are useful on the table view for quickly looking up potentially confusing/complex properties.

To remove the descriptions, simply remove the &lt;md-tooltip&gt; directives from the selected-elements.html.

**Comment by c015dariu** [comment]
Hi, I'd like to tackle this issue however I have a few questions.

I understand this issue is quite old on the backlog and components have changed, however looking at selected-elements.html I can't find any <md-tooltip> component or any similar tag that pulls information pertaining to the schema apart from the pure values of the edges/entities themselves. Does this tooltip still exist or has it been removed some many commits ago in a different issue?

Second question is, from what I can see of the UI based on road-traffic-demo ui, there doesn't seem to be any data on the vertex to describe the schema. What are the descriptions that this issue is trying to point out? Similarly I don't see the schema info that was stated on the table view however I'm most likely not understanding what the schema description is. So to put it simply, what is the schema description/ what makes up a schema description?

Cheers

**Comment by d47853** [comment]
Thanks for pointing this out. This issue seems to have been fixed in #638. I'll close this ticket.
