### ISSUE TITLE
Travis Build fails intermittently

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#758]
The Travis Build fails on the UI intermittently. The error broadcast is:
```
Tests in error: 
  QueryBuilderST.shouldBeAbleToRunParameterisedQueries:262->enterText:282 » ElementNotInteractable
```

Investigate the cause of this bug and upload a fix

**Comment by n288TJYRX** [comment]
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.github.klieber:phantomjs:tar.bz2:linux-x86_64:2.0.0 in central (http://repo.maven.apache.org/maven2)
 org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.github.klieber:phantomjs:tar.bz2:linux-x86_64:2.0.0 in central (http://repo.maven.apache.org/maven2)
I think It might be because of the version of the linux phantomjs its trying to find. Looks like that version doesn't exist. Maybe using another version will work? https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by n288TJYRX** [comment]
Looks like you can tell it to use a certain version of phantom.js in the pom.xml for the ui.  https://stackoverflow.com/questions/36681591/angular-jasmine-tests-fail-when-running-in-linux-unable-to-locate-phantomjs-bi

**Comment by d47853** [comment]
Merged into develop
