### ISSUE TITLE
Add Java 11 profile

### ISSUE THREAD

**Issue by t11947** [gchq/gaffer-tools#850]
This issue has been rescoped to add a feature not in  #995 

@GCHQDeveloper314 said: "It was decided that the POM for Gaffer Tools should have a Java 11 profile to automatically create Java 11 code when a Suitable version of the JDK is used - the same as exists in Gaffer. This should be straightforward to do and will be done as part of the next release."

**Comment by t11947** [comment]
Edited ticket to remove modularisation from the scope.

**Comment by GCHQDeveloper314** [comment]
The work required for the Java 11 upgrade has been drafted in the [gh-850-java11 branch](https://github.com/gchq/gaffer-tools/compare/gh-850-java11). Not many changes were required beyond removing use of deprecated functionality that is removed in Gaffer v2. There is a problem with the `slider` module which relies on the Apache Slider project. This project [has been retired](https://lists.apache.org/thread/5zx17v4rwnl66ycwxskorr51v9k2zg39) and [hasn't been updated since March 2017](https://mvnrepository.com/artifact/org.apache.slider/slider-assembly). It is unable to work with recent versions of Hadoop/Accumulo. At least some functionality from Slider has been merged into Hadoop YARN. A decision needs to be taken about Slider as this blocks any upgrade to version 2.

**Comment by GCHQDeveloper314** [comment]
The changes in Gaffer itself and in #995 are sufficient for Gaffer Tools to build with Java 11.

**Comment by GCHQDeveloper314** [comment]
In fact, we don't need to add a Java 11 profile. The profile from Gaffer which enables Java 11 is inherited though the Gaffer POM and is now automatically used in Gaffer Tools. No further work is therefore required to add a profile to Gaffer Tools. This issue can now be closed.

**Comment by t92549** [comment]
> In fact, we don't need to add a Java 11 profile. The profile from Gaffer which enables Java 11 is inherited though the Gaffer POM and is now automatically used in Gaffer Tools. No further work is therefore required to add a profile to Gaffer Tools. This profile has been tested and Gaffer Tools is working correctly with Java 11. This issue can now be closed.

This issue has been retroactively added to the alpha 2 release notes as it is a new feature that was enabled by upgrading tools to work with alpha 2.
