### ISSUE TITLE
Remove gafferpy in its entirety

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-tools#964]
The gafferpy python shell was deprecated in #951. Remove it from Gaffer 2.0. 

Perhaps leave it while replacement being developed.

**Comment by t92549** [comment]
It has been instead decided that rather than deleting gafferpy in favour of fishbowl, gafferpy should remain available how it is going forward into Gaffer 2. Instead, fishbowl will be used to generate some parts of gafferpy, and the resulting library code will be released.
This should let users continue to use gafferpy how they used to, which will work for default Gaffer graphs, while also reducing maintenance effort. However, this will also let advanced users generate their own gafferpy library using fishbowl to suit their own custom graphs which have custom operations. This will be explained and documented alongside the fishbowl / gafferpy upgrade work as part of Gaffer 2.
